name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
      - "main"
  push:
    branches:
      - "*.x"
      - "main"
      - "feat/upgrade-to-laravel-13"

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install Dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: highest
          composer-options: --prefer-dist
      - name: Run coding standards
        run: vendor/bin/phpcs

